import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:image_picker/image_picker.dart';
import 'package:http/http.dart' as http;
import 'package:appwrite/appwrite.dart';
import '../services/distribution_service.dart';
import '../services/appwrite_service.dart';

const String _kFaceVerifyUrl =
    'https://pasteshub404-navikarana-backend.hf.space/login-face';

class AdminScanPage extends StatefulWidget {
  final String eventId;
  final String eventTitle;
  final String adminId;

  const AdminScanPage({
    super.key,
    required this.eventId,
    required this.eventTitle,
    required this.adminId,
  });

  @override
  State<AdminScanPage> createState() => _AdminScanPageState();
}

class _AdminScanPageState extends State<AdminScanPage> {
  final MobileScannerController _scanCtrl = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
  );
  final _manualCtrl = TextEditingController();

  bool _processing = false;
  _ScanFeedback? _feedback;
  bool _sheetOpen = false; // pause scanner while sheet is visible

  @override
  void dispose() {
    _scanCtrl.dispose();
    _manualCtrl.dispose();
    super.dispose();
  }

  // â”€â”€ QR decoded â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _handleRawQr(String raw) async {
    if (_processing || _sheetOpen) return;
    final userId = DistributionService.decodeQr(raw);
    if (userId == null) {
      _showFeedback(_ScanFeedback(
        status: _FeedbackStatus.error,
        headline: "Invalid QR Code",
        sub: "Not generated by upasthiti.",
      ));
      return;
    }
    await _openVerificationSheet(userId);
  }

  // â”€â”€ Load user & open sheet â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _openVerificationSheet(String userId) async {
    if (_sheetOpen) return;
    setState(() {
      _sheetOpen = true;
      _processing = true;
    });

    // Fetch user details from Appwrite
    Map<String, dynamic>? userData;
    try {
      final res = await AppwriteService.databases.listDocuments(
        databaseId: AppwriteService.databaseId,
        collectionId: 'users',
        queries: [Query.equal('username', userId), Query.limit(1)],
      );
      if (res.documents.isNotEmpty) userData = res.documents.first.data;
    } catch (_) {}

    if (!mounted) return;
    setState(() => _processing = false);

    await showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => _UserVerificationSheet(
        userId: userId,
        userData: userData,
        eventId: widget.eventId,
        adminId: widget.adminId,
        onIssued: (feedback) {
          Navigator.pop(ctx);
          _showFeedback(feedback);
        },
      ),
    );

    if (mounted) setState(() => _sheetOpen = false);
  }

  void _submitManual() {
    final id = _manualCtrl.text.trim();
    if (id.isNotEmpty) _openVerificationSheet(id);
  }

  void _showFeedback(_ScanFeedback fb) {
    if (!mounted) return;
    setState(() => _feedback = fb);
    Future.delayed(const Duration(seconds: 5), () {
      if (mounted) setState(() => _feedback = null);
    });
  }

  // â”€â”€ Build â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  @override
  Widget build(BuildContext context) {
    final isWindows = Platform.isWindows;

    return Scaffold(
      backgroundColor: const Color(0xFF101010),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        foregroundColor: Colors.white,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text("Scan QR Codes",
                style: GoogleFonts.poppins(
                    fontWeight: FontWeight.bold, fontSize: 16)),
            Text(widget.eventTitle,
                style: GoogleFonts.poppins(fontSize: 11, color: Colors.white60),
                overflow: TextOverflow.ellipsis),
          ],
        ),
        actions: [
          if (!isWindows)
            IconButton(
              icon: const Icon(Icons.flash_on),
              tooltip: "Toggle torch",
              onPressed: () => _scanCtrl.toggleTorch(),
            ),
        ],
      ),
      body: Stack(
        children: [
          isWindows ? _buildWindowsFallback() : _buildCamera(),
          Positioned(
            left: 16,
            right: 16,
            bottom: 32,
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 300),
              child: _feedback != null
                  ? _FeedbackBanner(
                      key: ValueKey(_feedback.hashCode), feedback: _feedback!)
                  : _processing
                      ? const _ProcessingBanner(key: ValueKey('proc'))
                      : const SizedBox.shrink(key: ValueKey('empty')),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCamera() {
    return Stack(
      children: [
        MobileScanner(
          controller: _scanCtrl,
          onDetect: (capture) {
            for (final barcode in capture.barcodes) {
              final raw = barcode.rawValue;
              if (raw != null) _handleRawQr(raw);
            }
          },
        ),
        Center(
          child: Container(
            width: 240,
            height: 240,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.white, width: 2),
              borderRadius: BorderRadius.circular(16),
            ),
            child: Stack(children: _corners()),
          ),
        ),
        Align(
          alignment: const Alignment(0, -0.25),
          child: Text("Point at recipient's QR code",
              style: GoogleFonts.poppins(color: Colors.white70, fontSize: 13)),
        ),
        Align(
          alignment: const Alignment(0, 0.65),
          child: TextButton.icon(
            onPressed: _showManualEntryDialog,
            icon: const Icon(Icons.keyboard_alt_outlined, color: Colors.white54),
            label: Text("Enter ID manually",
                style:
                    GoogleFonts.poppins(color: Colors.white54, fontSize: 12)),
          ),
        ),
      ],
    );
  }

  Widget _buildWindowsFallback() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.qr_code_scanner, size: 80, color: Colors.white30),
            const SizedBox(height: 20),
            Text(
              "Camera scanning unavailable on desktop.\nEnter the recipient's unique ID below.",
              textAlign: TextAlign.center,
              style:
                  GoogleFonts.poppins(color: Colors.white54, fontSize: 14),
            ),
            const SizedBox(height: 24),
            TextField(
              controller: _manualCtrl,
              style: const TextStyle(color: Colors.white),
              textInputAction: TextInputAction.done,
              onSubmitted: (_) => _submitManual(),
              decoration: InputDecoration(
                hintText: "Recipient Unique ID",
                hintStyle: const TextStyle(color: Colors.white38),
                filled: true,
                fillColor: const Color(0xFF1E1E1E),
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: BorderSide.none),
                focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(
                        color: Color(0xFF6A8A73), width: 1.5)),
                prefixIcon:
                    const Icon(Icons.badge_outlined, color: Colors.white38),
              ),
            ),
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _processing ? null : _submitManual,
                icon: const Icon(Icons.search),
                label: Text("Look Up & Verify",
                    style: GoogleFonts.poppins(fontWeight: FontWeight.bold)),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF6A8A73),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  void _showManualEntryDialog() {
    _manualCtrl.clear();
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: Text("Manual Entry",
            style: GoogleFonts.poppins(fontWeight: FontWeight.bold)),
        content: TextField(
          controller: _manualCtrl,
          autofocus: true,
          textInputAction: TextInputAction.done,
          onSubmitted: (_) {
            Navigator.pop(ctx);
            _submitManual();
          },
          decoration: const InputDecoration(
            hintText: "Recipient Unique ID",
            prefixIcon: Icon(Icons.badge_outlined),
          ),
        ),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: const Text("Cancel")),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF6A8A73),
                foregroundColor: Colors.white),
            onPressed: () {
              Navigator.pop(ctx);
              _submitManual();
            },
            child: const Text("Look Up"),
          ),
        ],
      ),
    );
  }

  // â”€â”€ Corner painter helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  List<Widget> _corners() {
    const c = Color(0xFF6A8A73);
    const size = 20.0;
    const thick = 3.0;
    return [
      Positioned(top: 0, left: 0, child: _corner(c, size, thick, tl: true)),
      Positioned(top: 0, right: 0, child: _corner(c, size, thick, tr: true)),
      Positioned(bottom: 0, left: 0, child: _corner(c, size, thick, bl: true)),
      Positioned(bottom: 0, right: 0, child: _corner(c, size, thick, br: true)),
    ];
  }

  Widget _corner(Color c, double size, double thick,
      {bool tl = false, bool tr = false, bool bl = false, bool br = false}) {
    return SizedBox(
      width: size,
      height: size,
      child: CustomPaint(
        painter: _CornerPainter(
            color: c,
            thickness: thick,
            topLeft: tl,
            topRight: tr,
            bottomLeft: bl,
            bottomRight: br),
      ),
    );
  }
}

// =============================================================================
// User Verification Sheet
// =============================================================================

class _UserVerificationSheet extends StatefulWidget {
  final String userId;
  final Map<String, dynamic>? userData;
  final String eventId;
  final String adminId;
  final void Function(_ScanFeedback) onIssued;

  const _UserVerificationSheet({
    required this.userId,
    required this.userData,
    required this.eventId,
    required this.adminId,
    required this.onIssued,
  });

  @override
  State<_UserVerificationSheet> createState() => _UserVerificationSheetState();
}

enum _VerifyStep { idle, capturingFace, verifying, issuing }

class _UserVerificationSheetState extends State<_UserVerificationSheet> {
  _VerifyStep _step = _VerifyStep.idle;
  String? _stepMessage;
  File? _capturedFace;

  String get _name =>
      widget.userData?['name'] as String? ?? widget.userId;
  String get _dept =>
      widget.userData?['department'] as String? ?? 'â€”';

  // â”€â”€ Face capture â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _captureAndVerify() async {
    // Step 1: capture face photo
    if (Platform.isWindows) {
      // Windows: skip face verification, issue directly after confirmation
      await _issuePackage(skipFace: true);
      return;
    }

    setState(() {
      _step = _VerifyStep.capturingFace;
      _stepMessage = "Opening camera...";
    });

    XFile? photo;
    try {
      photo = await ImagePicker().pickImage(
        source: ImageSource.camera,
        preferredCameraDevice: CameraDevice.front,
        maxWidth: 640,
        maxHeight: 640,
        imageQuality: 90,
      );
    } catch (_) {}

    if (photo == null) {
      setState(() {
        _step = _VerifyStep.idle;
        _stepMessage = null;
      });
      return;
    }

    _capturedFace = File(photo.path);

    // Step 2: verify face
    setState(() {
      _step = _VerifyStep.verifying;
      _stepMessage = "Verifying identity...";
    });

    final error = await _verifyFaceOnBackend(_capturedFace!, widget.userId);

    if (!mounted) return;

    if (error != null) {
      setState(() {
        _step = _VerifyStep.idle;
        _stepMessage = null;
      });
      widget.onIssued(_ScanFeedback(
        status: _FeedbackStatus.error,
        headline: "Face Verification Failed",
        sub: error,
      ));
      return;
    }

    // Step 3: issue package
    await _issuePackage(skipFace: false);
  }

  Future<String?> _verifyFaceOnBackend(File photo, String username) async {
    try {
      final request =
          http.MultipartRequest('POST', Uri.parse(_kFaceVerifyUrl));
      request.fields['username'] = username;
      request.files
          .add(await http.MultipartFile.fromPath('image', photo.path));
      final streamed = await request.send();
      final body = await streamed.stream.bytesToString();
      final decoded = jsonDecode(body) as Map<String, dynamic>;
      if (decoded['verified'] == true) return null;
      return decoded['error'] as String? ?? 'Face not recognised.';
    } catch (_) {
      return 'Could not reach the server.';
    }
  }

  Future<void> _issuePackage({required bool skipFace}) async {
    if (!mounted) return;
    setState(() {
      _step = _VerifyStep.issuing;
      _stepMessage = "Issuing package...";
    });

    final result = await DistributionService.processQrScan(
      eventId: widget.eventId,
      scannedUserId: widget.userId,
      adminId: widget.adminId,
    );

    if (!mounted) return;

    _ScanFeedback fb;
    switch (result.status) {
      case ScanStatus.success:
        fb = _ScanFeedback(
          status: _FeedbackStatus.success,
          headline: skipFace
              ? "Package Issued (face skipped on desktop)"
              : "Package Issued âœ“ Face Verified",
          sub: result.userName ?? widget.userId,
        );
        break;
      case ScanStatus.alreadyIssued:
        final when = result.issuedAt != null ? _fmt(result.issuedAt!) : 'earlier';
        fb = _ScanFeedback(
          status: _FeedbackStatus.warning,
          headline: "Already Issued",
          sub:
              "${result.userName ?? widget.userId} â€” $when by ${result.issuedBy ?? '?'}",
        );
        break;
      case ScanStatus.notInList:
        fb = _ScanFeedback(
          status: _FeedbackStatus.error,
          headline: "Not on Recipient List",
          sub: widget.userId,
        );
        break;
      case ScanStatus.revoked:
        fb = _ScanFeedback(
          status: _FeedbackStatus.error,
          headline: "Recipient Revoked",
          sub: result.userName ?? widget.userId,
        );
        break;
      case ScanStatus.eventNotActive:
        fb = _ScanFeedback(
          status: _FeedbackStatus.error,
          headline: "Event Not Active",
          sub: "This event is no longer accepting scans.",
        );
        break;
      case ScanStatus.notAuthorized:
        fb = _ScanFeedback(
          status: _FeedbackStatus.error,
          headline: "Not Authorized",
          sub: "You are not assigned to this event.",
        );
        break;
    }

    widget.onIssued(fb);
  }

  String _fmt(String iso) {
    try {
      final dt = DateTime.parse(iso).toLocal();
      return "${dt.day}/${dt.month} ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}";
    } catch (_) {
      return iso;
    }
  }

  // â”€â”€ Build â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                  color: Colors.grey.shade300,
                  borderRadius: BorderRadius.circular(2)),
            ),
          ),
          const SizedBox(height: 20),

          // User card
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFFF8F9FB),
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.grey.shade200),
            ),
            child: Row(
              children: [
                CircleAvatar(
                  radius: 30,
                  backgroundColor: const Color(0xFF6A8A73).withValues(alpha: 0.15),
                  child: Text(
                    _name.isNotEmpty ? _name[0].toUpperCase() : '?',
                    style: const TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFF6A8A73)),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(_name,
                          style: GoogleFonts.poppins(
                              fontSize: 16, fontWeight: FontWeight.bold)),
                      const SizedBox(height: 2),
                      Text(widget.userId,
                          style: GoogleFonts.poppins(
                              fontSize: 12, color: Colors.grey.shade500)),
                      const SizedBox(height: 2),
                      Text(_dept,
                          style: GoogleFonts.poppins(
                              fontSize: 11, color: Colors.grey.shade500)),
                    ],
                  ),
                ),
                const Icon(Icons.qr_code_2_rounded,
                    color: Color(0xFF6A8A73), size: 28),
              ],
            ),
          ),

          const SizedBox(height: 20),

          // Status / step indicator
          if (_step != _VerifyStep.idle) ...[
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              decoration: BoxDecoration(
                color: const Color(0xFF6A8A73).withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                  const SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(
                        strokeWidth: 2, color: Color(0xFF6A8A73)),
                  ),
                  const SizedBox(width: 12),
                  Text(_stepMessage ?? '',
                      style: GoogleFonts.poppins(
                          fontSize: 13, color: const Color(0xFF6A8A73))),
                ],
              ),
            ),
            const SizedBox(height: 16),
          ],

          // Face scan instruction
          if (_step == _VerifyStep.idle && !Platform.isWindows) ...[
            Row(
              children: [
                const Icon(Icons.face_retouching_natural,
                    size: 16, color: Colors.grey),
                const SizedBox(width: 6),
                Text(
                  "Face verification required before issuing",
                  style: GoogleFonts.poppins(
                      fontSize: 12, color: Colors.grey.shade600),
                ),
              ],
            ),
            const SizedBox(height: 14),
          ],

          // Action button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _step != _VerifyStep.idle ? null : _captureAndVerify,
              icon: Icon(Platform.isWindows
                  ? Icons.inventory_2_outlined
                  : Icons.face_retouching_natural),
              label: Text(
                Platform.isWindows
                    ? "Issue Package"
                    : "Scan Face & Issue Package",
                style: GoogleFonts.poppins(fontWeight: FontWeight.bold),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF6A8A73),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(14)),
                elevation: 0,
              ),
            ),
          ),
          const SizedBox(height: 8),
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text("Cancel",
                style: GoogleFonts.poppins(color: Colors.grey.shade500)),
          ),
        ],
      ),
    );
  }
}

// =============================================================================
// Corner painter
// =============================================================================

class _CornerPainter extends CustomPainter {
  final Color color;
  final double thickness;
  final bool topLeft, topRight, bottomLeft, bottomRight;

  const _CornerPainter({
    required this.color,
    required this.thickness,
    this.topLeft = false,
    this.topRight = false,
    this.bottomLeft = false,
    this.bottomRight = false,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final p = Paint()
      ..color = color
      ..strokeWidth = thickness
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;
    final w = size.width;
    final h = size.height;
    if (topLeft) {
      canvas.drawLine(Offset(0, h), Offset.zero, p);
      canvas.drawLine(Offset.zero, Offset(w, 0), p);
    }
    if (topRight) {
      canvas.drawLine(Offset(0, 0), Offset(w, 0), p);
      canvas.drawLine(Offset(w, 0), Offset(w, h), p);
    }
    if (bottomLeft) {
      canvas.drawLine(Offset(0, 0), Offset(0, h), p);
      canvas.drawLine(Offset(0, h), Offset(w, h), p);
    }
    if (bottomRight) {
      canvas.drawLine(Offset(w, 0), Offset(w, h), p);
      canvas.drawLine(Offset(w, h), Offset(0, h), p);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter _) => false;
}

// =============================================================================
// Feedback models and widgets
// =============================================================================

enum _FeedbackStatus { success, warning, error }

class _ScanFeedback {
  final _FeedbackStatus status;
  final String headline;
  final String sub;
  const _ScanFeedback(
      {required this.status, required this.headline, required this.sub});
}

class _FeedbackBanner extends StatelessWidget {
  final _ScanFeedback feedback;
  const _FeedbackBanner({super.key, required this.feedback});

  @override
  Widget build(BuildContext context) {
    final colors = {
      _FeedbackStatus.success: [
        const Color(0xFF1B5E20),
        const Color(0xFF4CAF50)
      ],
      _FeedbackStatus.warning: [
        const Color(0xFF4A3000),
        const Color(0xFFFFB300)
      ],
      _FeedbackStatus.error: [
        const Color(0xFF4A0000),
        const Color(0xFFEF5350)
      ],
    }[feedback.status]!;

    final icons = {
      _FeedbackStatus.success: Icons.check_circle_rounded,
      _FeedbackStatus.warning: Icons.warning_amber_rounded,
      _FeedbackStatus.error: Icons.cancel_rounded,
    }[feedback.status]!;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      decoration: BoxDecoration(
        color: colors[0],
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: colors[1].withValues(alpha: 0.4)),
      ),
      child: Row(
        children: [
          Icon(icons, color: colors[1], size: 28),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(feedback.headline,
                    style: GoogleFonts.poppins(
                        color: colors[1],
                        fontWeight: FontWeight.bold,
                        fontSize: 14)),
                Text(feedback.sub,
                    style:
                        GoogleFonts.poppins(color: Colors.white70, fontSize: 12),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _ProcessingBanner extends StatelessWidget {
  const _ProcessingBanner({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
      decoration: BoxDecoration(
        color: const Color(0xFF1A1A1A),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.white12),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          const SizedBox(
            width: 18,
            height: 18,
            child: CircularProgressIndicator(
                strokeWidth: 2, color: Color(0xFF6A8A73)),
          ),
          const SizedBox(width: 14),
          Text("Loading recipient details...",
              style:
                  GoogleFonts.poppins(color: Colors.white70, fontSize: 13)),
        ],
      ),
    );
  }
}


