name: upasthiti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  file_picker: ^10.3.8
  http: ^1.6.0
  geolocator: ^10.1.0
  camera: ^0.11.3
  path_provider: ^2.1.5
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2
  desktop_multi_window: ^0.3.0
  webview_windows: ^0.4.0
  crypto: ^3.0.6
  flutter_map: ^8.2.2 
  latlong2: ^0.9.1
  google_mlkit_face_detection: ^0.11.0
  csv: ^6.0.0
  permission_handler: ^12.0.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  appwrite: ^23.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  excel: ^4.0.6
  pdf: ^3.12.0
  printing: ^5.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/upasthiti.png

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/appLogo.png"
    icon_size: 48
  image_path: "assets/appLogo.png"
